### PR TITLE
Fix: #70, Reads after Connection close should only error when there is no more available data

### LINKED ISSUE #70: Reading Data after Connection Closed
Frisbee has a feature where reactor functions are able to write some data to the connection and then close that connection. The receiving Frisbee connection expects to be able to read the data from the connection until the connection is closed - however currently, even if there are unread packets in the incoming queue of a Frisbee connection, reading will error out once the sending side closes their connection.

### PR DESCRIPTION
**Pull request by ShivanshVij**
## Description

Please include a summary of the change and which issue has been fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- A `Drain` function was added to `internal/queue` to allow the `killGoroutines` function to drain the queue once it had closed it and once it had killed all existing goroutines
- The client `heartbeat` function was modified to exit early if it detected that the underlying connection had closed
- The `Async` connection type was modified to hold `stale` data once a connection is closed. The `killGoroutines` function will drain the `incoming` queue after killing all goroutines, and store those drained packets in the `Async.stale` variable - future and existing ReadPacket calls will first check whether there is data available in the `stale` variable before they error out
- The `close` function call in `Async` connections was modified to set a final write deadline for its final writer flush
- Refactored the `handlePacket` functions for both servers and clients to be clearer and avoid allocations

Fixes #70

## Type of change

**Please update the title of this PR to reflect the type of change.** (Delete the ones that aren't required).

- [x] Bug fix (non-breaking change which fixes an issue) [title: 'fix:']

## Testing

Please make sure that existing test cases pass (with `go test ./... -race` and `go test -bench=. ./... -race`),
and if required please add new test cases and list them below:

- [x] TestAsyncReadAvailableClose
- [x] TestServerStaleClose
- [x] TestClientStaleClose

## Benchmarking

Frisbee tries to adhere to strict performance requirements, so please make sure to run `go test -bench=. ./...` and paste the results below:

### Benchmarking Results:

```shell
goos: darwin
goarch: arm64
pkg: github.com/loopholelabs/frisbee
BenchmarkAsyncThroughputPipe/32_Bytes-10                  104292             11535 ns/op         277.41 MB/s         450 B/op          8 allocs/op
BenchmarkAsyncThroughputPipe/512_Bytes-10                  67843             17717 ns/op        2889.94 MB/s         450 B/op          8 allocs/op
BenchmarkAsyncThroughputPipe/1024_Bytes-10                 56389             21190 ns/op        4832.48 MB/s         450 B/op          8 allocs/op
BenchmarkAsyncThroughputPipe/2048_Bytes-10                 40431             29713 ns/op        6892.62 MB/s         451 B/op          8 allocs/op
BenchmarkAsyncThroughputPipe/4096_Bytes-10                 24122             49577 ns/op        8261.95 MB/s         463 B/op          8 allocs/op
BenchmarkAsyncThroughputNetwork/32_Bytes-10                46525             26475 ns/op         120.87 MB/s         257 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/512_Bytes-10               36973             32222 ns/op        1588.99 MB/s         257 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/1024_Bytes-10              31856             37784 ns/op        2710.17 MB/s         257 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/2048_Bytes-10              24055             49616 ns/op        4127.67 MB/s         259 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/4096_Bytes-10              16674             72020 ns/op        5687.32 MB/s         257 B/op          4 allocs/op
BenchmarkThroughputClient/test-10                             80          15630455 ns/op        2146.70 MB/s        4146 B/op          6 allocs/op
BenchmarkThroughputResponseClient/test-10                     74          16244046 ns/op        2065.61 MB/s        4523 B/op          2 allocs/op
BenchmarkThroughputServer/test-10                            114          10267932 ns/op        3267.84 MB/s        3976 B/op          1 allocs/op
BenchmarkThroughputResponseServer/test-10                    121           9903261 ns/op        3388.17 MB/s        2381 B/op          3 allocs/op
BenchmarkSyncThroughputPipe/32_Bytes-10                     7434            145954 ns/op          21.92 MB/s        1858 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/512_Bytes-10                    7282            145738 ns/op         351.32 MB/s        1857 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/1024_Bytes-10                   8126            146635 ns/op         698.33 MB/s        1860 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/2048_Bytes-10                   7977            147397 ns/op        1389.45 MB/s        1859 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/4096_Bytes-10                   7984            150511 ns/op        2721.40 MB/s        1865 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/32_Bytes-10                  3249            327235 ns/op           9.78 MB/s        1857 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/512_Bytes-10                 3075            344782 ns/op         148.50 MB/s        1857 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/1024_Bytes-10                2922            345925 ns/op         296.02 MB/s        1862 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/2048_Bytes-10                3210            351161 ns/op         583.21 MB/s        1862 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/4096_Bytes-10                3226            355124 ns/op        1153.40 MB/s        1868 B/op        204 allocs/op
BenchmarkAsyncThroughputLarge/1MB-10                         156           8039303 ns/op        13043.12 MB/s      86786 B/op          4 allocs/op
BenchmarkAsyncThroughputLarge/2MB-10                          61          16844812 ns/op        12449.84 MB/s     358628 B/op          5 allocs/op
BenchmarkAsyncThroughputLarge/4MB-10                          24          55381358 ns/op        7573.49 MB/s     1673928 B/op          8 allocs/op
BenchmarkAsyncThroughputLarge/8MB-10                           8         126047797 ns/op        6655.10 MB/s     5922318 B/op         13 allocs/op
BenchmarkAsyncThroughputLarge/16MB-10                          4         262948708 ns/op        6380.41 MB/s    19663306 B/op         20 allocs/op
BenchmarkSyncThroughputLarge/1MB-10                           80          14436041 ns/op        7263.60 MB/s     2819653 B/op        221 allocs/op
BenchmarkSyncThroughputLarge/2MB-10                           40          29143953 ns/op        7195.84 MB/s     1061062 B/op        207 allocs/op
BenchmarkSyncThroughputLarge/4MB-10                           21          57441837 ns/op        7301.83 MB/s    20106985 B/op        240 allocs/op
BenchmarkSyncThroughputLarge/8MB-10                            9         125012273 ns/op        6710.23 MB/s    46340782 B/op        249 allocs/op
BenchmarkSyncThroughputLarge/16MB-10                           4         263560260 ns/op        6365.61 MB/s    102638996 B/op       249 allocs/op
BenchmarkTCPThroughput/32_Bytes-10                         19956             60020 ns/op          53.32 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/512_Bytes-10                        12622             95641 ns/op         535.34 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/1024_Bytes-10                        8493            140516 ns/op         728.74 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/2048_Bytes-10                        5278            239875 ns/op         853.78 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/4096_Bytes-10                        2762            444297 ns/op         921.91 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/1MB-10                                 85          14096236 ns/op        7438.69 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/2MB-10                                 40          28997252 ns/op        7232.24 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/4MB-10                                 19          59525778 ns/op        7046.20 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/8MB-10                                  9         123547968 ns/op        6789.76 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/16MB-10                                 4         255130854 ns/op        6575.93 MB/s         304 B/op          4 allocs/op
PASS
ok      github.com/loopholelabs/frisbee 77.998s
PASS
ok      github.com/loopholelabs/frisbee/internal/queue  0.161s
```

## Linting

Please make sure you've run the following and fixed any issues that arise:

- [x] `trunk check` has been run

## Final Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: async_test.go [hunk 1]
```diff
@@ -245,6 +245,56 @@ func TestAsyncReadClose(t *testing.T) {
...
+	require.NoError(t, err)
+
+	packet.Put(p)
+
+	err = writerConn.Close()
+	require.NoError(t, err)
+
+	p, err = readerConn.ReadPacket()
+	require.NoError(t, err)
+	assert.NotNil(t, p.Metadata)
```
Comment (Jspsun) [inline async_test.go:275]: nit: this should be a require

File: async_test.go [hunk 2]
```diff
@@ -245,6 +245,56 @@ func TestAsyncReadClose(t *testing.T) {
...
+	assert.Equal(t, uint16(64), p.Metadata.Id)
+	assert.Equal(t, uint16(32), p.Metadata.Operation)
+	assert.Equal(t, uint32(0), p.Metadata.ContentLength)
+	assert.Equal(t, 0, len(p.Content.B))
+
+	p, err = readerConn.ReadPacket()
+	require.NoError(t, err)
+	assert.NotNil(t, p.Metadata)
```
Comment (Jspsun) [inline async_test.go:283]: nit: should be a require

**Review by Jspsun — APPROVED** [review]
very minor nits
